apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "universal-messaging.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "universal-messaging.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "universal-messaging.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "universal-messaging.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      serviceAccountName: {{ include "universal-messaging.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: nsp
              containerPort: 9000
              protocol: TCP
          volumeMounts:
          - name: data
            mountPath: /opt/softwareag/UniversalMessaging/server/umserver/data
          - name: logs
            mountPath: /opt/softwareag/UniversalMessaging/server/umserver/logs
          - name: configuration
            mountPath: /opt/softwareag/common/conf

          #livenessProbe:
          #   exec:
          #      command:
          #      - runUMTool.sh
          #      - GetServerTime
          #      - -rname=nsp://localhost:{{ .Values.port }}
          #   initialDelaySeconds: 30
          #   periodSeconds: 15
          #readinessProbe:
          #   exec:
          #      command:
          #      - runUMTool.sh
          #      - GetServerTime
          #      - -rname=nsp://localhost:{{ .Values.port }}
          #   initialDelaySeconds: 30
          #   periodSeconds: 15
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      - name: configuration
        persistentVolumeClaim:
          claimName: {{ include "universal-messaging.fullname" . }}-configuration
      - name: logs
        persistentVolumeClaim:
          claimName: {{ include "universal-messaging.fullname" . }}-logs
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "universal-messaging.fullname" . }}-data

