apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "universal-messaging.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "universal-messaging.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "universal-messaging.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "universal-messaging.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ include "universal-messaging.fullname" . }}-{{ .Values.imagePullSecret }}
      serviceAccountName: {{ include "universal-messaging.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: nsp
              containerPort: 9000
              protocol: TCP
          volumeMounts:
          - name: data
            mountPath: /opt/softwareag/UniversalMessaging/server/umserver/data
          - name: logs
            mountPath: /opt/softwareag/UniversalMessaging/server/umserver/logs
          - name: configuration
            mountPath: /opt/softwareag/common/conf
      {{- if .Values.licenseFile }}
          - name: licenses
            mountPath: /opt/softwareag/IntegrationServer/config/licenseKey.xml
            subPath: licenseKey.xml
      {{- end }}
      {{- if .Values.files }}
         {{ $values := .Values }}
        {{ range $key, $val := .Values.files }}
          - name: files-map
            mountPath: {{ $val }}{{ $key }}
            subPath: {{ $key }}
        {{- end }}
      {{- end }}
          env:
          {{- if .Values.configURL }}
          - name: UMconfigURL
            value: {{ .Values.configURL }}
          {{- end }}
          {{- if .Values.envVariables }}
          {{- range $key, $val := .Values.envVariables }}
          - name: {{ $key }}
            value: {{ $val }}
          {{- end }}
          {{- end }}


          #livenessProbe:
          #   exec:
          #      command:
          #      - runUMTool.sh
          #      - GetServerTime
          #      - -rname=nsp://localhost:{{ .Values.port }}
          #   initialDelaySeconds: 30
          #   periodSeconds: 15
          #readinessProbe:
          #   exec:
          #      command:
          #      - runUMTool.sh
          #      - GetServerTime
          #      - -rname=nsp://localhost:{{ .Values.port }}
          #   initialDelaySeconds: 30
          #   periodSeconds: 15
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      - name: configuration
        persistentVolumeClaim:
          claimName: {{ include "universal-messaging.fullname" . }}-configuration
      - name: logs
        persistentVolumeClaim:
          claimName: {{ include "universal-messaging.fullname" . }}-logs
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "universal-messaging.fullname" . }}-data
      {{- if .Values.licenseFile }}
      - name: licenses
        configMap:
          name: {{ include "universal-messaging.fullname" . }}-license-config-map
      {{- end }}
      {{- if .Values.files }}
      - name: files-map
        configMap:
          name: {{ include "universal-messaging.fullname" . }}-files-config-map
      {{- end }}
