apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "universal-messaging.fullname" . }}-configuration
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
