{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "universal-messaging.serviceAccountName" . }}
  labels:
{{ include "universal-messaging.labels" . | nindent 4 }}
{{- end -}}
