#!/usr/bin/env groovy

pipeline {
    agent {
        label 'docker1'
    }
    options {
        buildDiscarder(logRotator(numToKeepStr:'10'))
        disableConcurrentBuilds()
    }
    environment {
        COMPOSE_FILE = 'docker-compose.yml'
    }
    stages {
        stage('Initialize'){
            steps {
                sh 'chmod -R 777 ${WORKSPACE}'
            }
        }
    stages {
        stage("Pull") {
            steps {
                sh 'docker-compose down' 
                sh 'docker-compose pull'
            }
        } 
        stage('Build'){
            steps {
                sh 'docker-compose build --no-cache microservices-runtime'
                sh 'MSR_JDBC_URL="jdbc:mysql://mysql:3306/webm" MSR_JDBC_PASSWORD=webm MSR_JDBC_USER=webm MSR_JNDI_PROVIDER_URL="nsp://universal-messaging:9000" docker-compose up microservices-runtime'
                }
        }
	stage('Deploy'){
            steps {
                sh 'docker-compose push microservices-runtime'
            }
        }
    }
}