apiVersion: v2
name: webm-um-msr
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: 1.16.0
dependencies:
- name:  universal-messaging
  version: "0.1.0"
  repository: "https://npapazov.github.io/webm-azure-devops/chart-repo"
- name: microservices-runtime
  version: "0.1.0"
  repository: "https://npapazov.github.io/webm-azure-devops/chart-repo"
