{{- if .Values.envVariables }}
apiVersion: v1
kind: ConfigMap
metadata:
  name:  {{ include "microservices-runtime.fullname" . }}-environment-variables-config-map
  namespace: {{ .Release.Namespace }}
data:
{{- range $key, $val := .Values.envVariables }}
  {{ $key }}: {{ $val }} 
{{- end }}
{{- end -}}
