apiVersion: v1
kind: Secret
metadata:
  name: {{ include "microservices-runtime.fullname" . }}-{{ .Values.imagePullSecret }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }} 
